### PR TITLE
Highlight categories and compact navbar

### PR DESCRIPTION
**Pull request by fflaten**
Separate pages from categories in navbar by reducing font-size on links

### CODE REVIEW

**Comment by fflaten** [comment]
Just experimenting with a more compact navbar style. Thoughts? Is it more readable?

Couldn't find a use for `.navbar__brand strong` css selector, but might have missed something.

**Comment by bravo-kernel** [comment]
I like the smaller font size for the sub pages, not a fan of the bold for main categories though.

Please let me know what you want to do, merge or...

**Comment by fflaten** [comment]
That works too. Fixed 🙂

**Comment by bravo-kernel** [comment]
Very nice, how come we never thought of smaller fonts before 🙄

**Comment by fflaten** [comment]
🤷‍♂️ Got inspired by Starlight's (Astro's Docusaurus equivalent) style after I realized our categories weren't links.

**Pull request merged**
