### PR TITLE
Add more info to improving the command help

### PR DESCRIPTION
**Pull request by nohwnd**
Add more info to point out that improving the help for a command is possible, but not by sending a PR here.

### CODE REVIEW

**Comment by nohwnd** [comment]
@bravo-kernel what do you think? To me it read like we don't accept PRs for the help docs at all. And without knowing how it works, I would not be able to figure out how to improve the docs for a command if I wanted to do it.

**Comment by bravo-kernel** [comment]
You are right and I remember we once had something more explicit before we started stripping ;). I would personally inform them first, then explain were to go.

```
🔥 This page is auto-generated using the Pester Get-Help documentation for this command.

To improve the command documentation, make a PR to the Pester source files in the [pester/Pester](https://github.com/pester/Pester) repository.
```

**Reminder:** if the Pester repo was using a `file-per-function` we would not need this footer and the `Edit this Page` link would point straight to the correlating Pester source file.

**Comment by nohwnd** [comment]
> if the Pester repo was using a file-per-function...

That will happen at some point. :)

**Comment by bravo-kernel** [comment]
Yeah, I remember you explaining that splitting would be a huge task by itself. Step by step my friend :)

**Pull request merged**
