### PR TITLE
Example of asserting expected exception was thrown

### PR DESCRIPTION
**Pull request by robhalevt**
Adding an example of how to assert an expected exception is being thrown

### CODE REVIEW

**Comment by nohwnd** [comment]
Thanks!

**Comment by fflaten** [comment]
This is command reference. Should've been added in pester-source.

**Comment by nohwnd** [comment]
Aaargh, right! Thanks for pointing that out.

**Comment by nohwnd** [comment]
Created #181 for it so we don't lose this update even if OP decides to not create the new PR. Sorry for the confusion and thanks for the update.

**Pull request merged**
