### PR TITLE
Add missing Emoji and Fruit sample functions

### LINKED ISSUE #140: Cannot follow / test examples without Get-Emoji.ps1
## Location
https://pester-docs.netlify.app/docs/usage/data-driven-tests

- Pester version: 5.2.2

## General summary of the issue

I'm trying to take a working copy of code (e.g. code from the documentation) and run this locally to test and tweak to help me understand how the data driven aspects of Pester behave (sometimes long documentation is harder to understand than getting hands on with things). Without Get-Emoji.ps1 it's not possible to run any of this because the function doesn't exist (obviously!). Please could this file be added to the documentation to download so we can import it? Thank you.

### PR DESCRIPTION
**Pull request by fflaten**
Fix #140

### CODE REVIEW

**Comment by fflaten** [comment]
I should probably drop the class for pscustomobject so it works with all supported PS-versions.

**Comment by bravo-kernel** [comment]
I think (1) all-platform examples are the way to go (2) perhaps you could start using "good to merge" message once things are done.

**Comment by fflaten** [comment]
> perhaps you could start using "good to merge" message once things are done. 

It was good to merge, until I realized this compatibility-issue on my way to work. Mobile app won't let me convert to draft PR, so left the comment until I can change it 🙂

**Comment by bravo-kernel** [comment]
Never noticed the "Draft PR" status before :-D

**Comment by fflaten** [comment]
TIL about `EnumerateRunes()` in .NET Core, so PS6+. Not sure when I'll need it, but thanks @nohwnd 😄 

After rewriting it I realized emojis don't work well in PS 5.1 either way so I also added "(PowerShell 6 or later)" to them. At least they can see the code and follow along.

**Comment by bravo-kernel** [comment]
This is very very cool 💃 

image

**Pull request merged**
