### PR TITLE
Set version of Pester via parameter

### PR DESCRIPTION
**Pull request by nohwnd**
The mimimum amount of work to set the Pester version externally. I think you already install it so I did not do that here. And I also assume that you don't have multiple other versions of Pester imported.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thanks for making it visible, if that `-RequiredVersion` works as expected this is a good starting point.

- I do have multiple Pester versions installed
- this still contains a hardcoded "latest version"
- I was thinking about fetching the latest version from e.g. PSGallery (if internet is available)

Feel free to merge this as a starting point though.

**Comment by bravo-kernel** [comment]
Do you think it is possible to install the specific (passed) module version if it is not installed ?

**Comment by nohwnd** [comment]
> Thanks for making it visible, if that `-RequiredVersion` works as expected this is a good starting point.
> 
> * I do have multiple Pester versions installed
> * this still contains a hardcoded "latest version"

that was just so you can run it easily interactively, I can remove that and make that parameter mandatory so you have to provide it externally

> * ~I was thinking about fetching the latest version from e.g. PSGallery (if internet is available)~ but that is not needed I think


> Do you think it is possible to install the specific (passed) module version if it is not installed ?

Yes if your environment is setup correctly. then it is just: Install-Module Pester -RequiredVersion $PesterVersion -Force -SkipPublisherCheck -AllowClobber
 

Will have a closer look later hopefully.

**Comment by bravo-kernel** [comment]
No worries, feel free to merge this in. Now that I have the base information I can take it from there (and you can focus on the Pester end).

**Pull request merged**
