### PR TITLE
Cleanup whitespace formatting

### PR DESCRIPTION
**Pull request by fflaten**
~~Apply editorconfig settings to both md and mdx files~~

Standardize whitespace across project. Trim trailing whiteline + end on newline also for markdown-files

### CODE REVIEW

**Comment by bravo-kernel** [comment]
I have no problem merging this but think we should first change both settings to `true`.

- the editorconfig in this repo is three years old and is docusaurus-generated
- docusaurus no longer includes editorconfig in newly generated sites
- for reasoning, check MD009 and MD047 in the [markdown linting rules](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md)

**Comment by fflaten** [comment]
I'm perfectly fine with that. Feel free to remove the whole MD/MDX section then.

The reason I even modified this was because my defaults in vscode made whitespace-changes on every line on save and I assumed my preference was wrong for MD 😁

**Comment by bravo-kernel** [comment]
I agree, if you could remove the section it would be great.

**Comment by bravo-kernel** [comment]
Awesome, very good job. Much ❤️

**Pull request merged**
