### PR TITLE
Website Theme (final review)

### PR DESCRIPTION
**Pull request by lex111**
## Live Preview

https://deploy-preview-29--pester-docs.netlify.com/

----

Resolving #28 

This is a preview version so that all Pester members can view the already updated website. Since the requirements are not complete, I could miss something and not finish, please write about this!

### CODE REVIEW

**Comment by bravo-kernel** [comment]
@nohwnd @deejaygraham **we need to start providing feedback, input, ideas here to not block progress**.

Could you please provide:

- "ok, going in the right direction" OR "nah, no good because x, y, z"

### Hero image

I do not like the Pester logo there, perhaps we could show some Powershell testing code? 

### Landing Page topics

I think it _could_ be a good idea to highlight Pester's strong points for the 4 sub-heros but... you folks need to come up with the selling points. I can imagine stuff like:

- VSCode integration
- Backwards Compatible
- Perhaps even... Version 5 coming up
- etc

image

**Comment by bravo-kernel** [comment]
@nohwnd our friend has implemented all theme changes and I must say that I'm pretty pleased with the result.

### I have agreed on the following steps:

1. communicate that the final-preview is available
2. give people until tomorrow to test/respond
3. after that.... I will green-light this, job well done

### To prevent misunderstandings:

- I will update the footer myself after merging
- we need to come up with good content for the landing page (the current "tdd" and "visual studio code" are just examples to give an idea)

### Lastly:

- the theme looks good on mobile too
- table width has been fixed

**Comment by nohwnd** [comment]
@bravo-kernel @lex111 

- In General -> yes it looks great, I have some minor nitpicks, especially around the mobile version. I will post them next. 

- Landing Page topics - all the topics you mentioned are great, I will try to write them soon, but probably not today. This should imho not block the bounty from being finished, because the current heros look good as they are.

- Main color - I prefer the lighter version as well


it looks great here are some minor thing:

- The font for "Pester" in the header on the desktop view is too small / thin, not sure if the same font is also use for the menu on the right side, but when I open the page, my eyes are drawn to the right to the menu. Please try making that text bigger / heavier / both.
image

Narrow view:
- the logo is too big
image
- menu is vertical
image

Mobile + narrow:
- hamburger menu is black
- menu text does not have enough contrast
image

Desktop view: 
The document part could imho take a bit more space, and still be comfortable for reading, the page would not look so empty. But maybe that is just my resolution / preference.
image


Fav icon: 
Fav icon is very blurry, I understand the logo is not great for this size but maybe you could try generating it from the version of the logo without background? (similar to github favicon).
image

**Comment by lex111** [comment]
All changes according to review are done, below are comments on some issues:

> The font for "Pester" in the header on the desktop view is too small / thin, not sure if the same font is also use for the menu on the right side, but when I open the page, my eyes are drawn to the right to the menu. Please try making that text bigger / heavier / both.

In fact, the font in navbar is the same for all elements inside, but in the logo brand it was made specifically light, I did it at the request of @bravo-kernel. I increased it, maybe it got better? Or do you still need to change to use bold font?

> The document part could imho take a bit more space, and still be comfortable for reading, the page would not look so empty. But maybe that is just my resolution / preference.

This is due to the fact that the default is fixed width for this container, therefore, the result is not very good on very large screens, although we can do it as on componentkit:

| Before   | After    |
| -------- | -------- |
| image | image |

Do we want that?

**Comment by nohwnd** [comment]
I dumped my cache, but still see the font as gray on blue in the mobile menu.
image

The font for Pester looks better now, and the favicon is great. 😊 The wide view I am not sure about, let's keep it as is.

**Comment by lex111** [comment]
@nohwnd are you sure you cleared the cache? Because I just checked on desktop and on my mobile, and color in the menu is white.

**Comment by lex111** [comment]
> The wide view I am not sure about, let's keep it as is.

I will raise this issue in Infima, this is a CSS framework that uses D2. I think we can and should find a solution for such large screens, because it does not look very good.

**Comment by nohwnd** [comment]
Yes, I have the cache disabled when developer panel is open in chrome and I got a new favicon, so I am quite sure. I also tried "Empty cache and hard reload" and still see the gray text (I see it as well on my phone and there I also see the new favicon).

**Comment by nohwnd** [comment]
👍

**Comment by lex111** [comment]
@nohwnd try again please.

**Comment by bravo-kernel** [comment]
@nohwnd About the width:

- we change the column width to mimic the componentkit org landing page
- that width was applied to the content pages as well

I have asked @lex111 to only apply the custom width to the landing page so we keep using D2 default values for content pages. This way.... we will benefit of all fixed applied to D2 (except for our landing page). 

Before the fix:

image

**Comment by bravo-kernel** [comment]
After applying custom-width to landing page only 💃 

image

**Comment by bravo-kernel** [comment]
@nohwnd I think all requested changes have been made and that the site looks prettyyyyy sweet 💯 .

Please confirm if you agree so we can merge and I can start fine tuning some of the texts.

**Comment by nohwnd** [comment]
Yes, please merge.

**Comment by bravo-kernel** [comment]
@nohwnd awesome, will you contact @lex111 on Discord to help him out with the bounty?

# ❤️ THANK YOU @lexx111 ❤️ 

You did an amazing job, nice working with you and thank you for your patience.

**Comment by nohwnd** [comment]
Bounty is completed. @lex111 please collect it by expensing the [Pester Open Collective](https://opencollective.com/pester) for $250.

**Comment by bravo-kernel** [comment]
@nohwnd you are a gentleman 😎

**Pull request merged**
