### PR TITLE
Improves generate-command-reference.ps1

### PR DESCRIPTION
**Pull request by bravo-kernel**
This PR is a follow-up to the discussion in #73 and #77 (@fflaten @phbits):

- now auto determines and installs the latest module versions (unless a specific Pester version is given)
- adds the Pester version used to generate the pages to the footer (see screenshot)
- prepares for CI/CD
- also contains the updated 5.1.0 command reference pages (as produced by the updated script)

> Hopefully this will make things easier moving forward.

image

### CODE REVIEW

**Comment by fflaten** [comment]
@bravo-kernel Looks good, but I did notice a few render-bugs in the preview that I don't quite understand.

- `BeforeDiscovery `+ `Context `example bugged indention. `BeforeEach `works
  - Any idea why? Thought it was single-line scriptblock like `It "..." { ... }`, but `BeforeDiscovery `example breaks on whitespace in `# ... test code`.
- Trailing linebreak inside `Add-Numbers` demo-function in `Context`-example. Where did it come from?
- Multiple commands still have broken codeblocks. I thought we didn't need markdown codeblock unless the example includes an empty line. 
  - https://deploy-preview-78--pester-docs.netlify.app/docs/commands/New-PesterContainer#example-1  (and 2)
  - https://deploy-preview-78--pester-docs.netlify.app/docs/commands/Mock#example-4
  - All ConvertTo-*, Export-* examples

I'll submit a PR in pester-repo to add missing links to online-version + rewrite BeforeDiscovery example (borrow from data-driven-tests page) as it's in poor condition. I can add fixes to the problems above there if necessary, but need some help to understand the cause first 👍

**Comment by bravo-kernel** [comment]
> I thought we didn't need markdown codeblock unless the example includes an empty line. 

Only if it's a one-line example. All others need to be code fenced.

**Comment by bravo-kernel** [comment]
As far as the indentation and newlines go, I looked at the numbers example in Context only. Based on the parsing order I see three possible causes:

1. pester code contains malformed indentation, etc. Not the case if I must believe my editor, the source code looks perfect
2. PlatyPs is creating the malformed markdown 
3. Docusaurus.Powershell is creating the malformed markdown

If (2) is the cause we can use (3) to make it look right again. Might not happen this week but I will take a look and, if things check out, will add the examples you mentioned to the Docusaurus testcases at https://github.com/alt3/Docusaurus.Powershell/tree/master/Tests/Integration.

**Comment by bravo-kernel** [comment]
Also, good to see you putting this effort in the documentation. Once it is up and up-to-date a lot of people will enjoy it, I'm sure. 💯

**Comment by bravo-kernel** [comment]
@nohwnd feel free to merge this one in. Step by step.

**Comment by bravo-kernel** [comment]
@fflaten I think you already know but just to be sure; markdown is fully supported within the get-help so you can use code elements, bold, bullets, etc . These are some good live examples:

- [argument description with bullets etc.](https://docusaurus-powershell.netlify.app/docs/commands/New-DocusaurusHelp#-vendoragnostic)
- [synopsis with code element](https://docusaurus-powershell.netlify.app/docs/commands/New-DocusaurusHelp#synopsis)

**Comment by bravo-kernel** [comment]
👍

**Pull request merged**
