### PR TITLE
Updated generated docs-notice in command reference

### PR DESCRIPTION
**Pull request by fflaten**
Trying out a prepended note-admonition in command ref pages to make it more intuitive where to submit updates. The current text is hidden at the end of very long pages.

Ref https://github.com/pester/docs/pull/257#issuecomment-1483853624

### CODE REVIEW

**Comment by fflaten** [comment]
Examples. Thoughts about text? Color? Placement?

Prepended (current PR):
image

Appended (felt a bit to hidden imo.):
image

**Comment by bravo-kernel** [comment]
Perhaps simplify the text, it has always felt way to long to understand instantly.

```
Do not edit this page but update the related [Pester](https://github.com/pester) source code instead.
```

Yellow color could be nice but perhaps you can share a screenshot?

**Comment by bravo-kernel** [comment]
Blue instead of yellow looking at https://docusaurus.io/docs/markdown-features/admonitions

**Comment by fflaten** [comment]
> Perhaps simplify the text, it has always felt way to long to understand instantly.
> 
> ```
> Do not edit this page but update the related [Pester](https://github.com/pester) source code instead.
> ```

Yeah, I noticed it took a lot of vertical space on my iPhone mini, so began looking at it.
Turns out the admonitions styles itself, especially margins in the title affect it the most, so shorter title didn't affect that much. Ex.

image

image

image


> Yellow color could be nice but perhaps you can share a screenshot?

Agree, but only if appended. On top it would take focus from the content (which it does slightly in dark mode already). It would also break with the site styling as this isn't really a caution/warning.

**Comment by fflaten** [comment]
> Blue instead of yellow looking at https://docusaurus.io/docs/markdown-features/admonitions

Good call. I'm feeling the blue a lot more in dark-mode too. 👍 
image

**Comment by bravo-kernel** [comment]
OK, let's stick with prepended and your suggested color but perhaps we can make the ammonition smaller:

- Caption: Do not edit this page
- Content: Update the related Pester 5.4.0 source instead.

Make Pester 5.4.0 a link?

**Comment by bravo-kernel** [comment]
Blue looks great, let's do that

------ Original Message ------
From: "Frode Flaten" ***@***.***>
To: "pester/docs" ***@***.***>
Cc: "bravo-kernel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-03-26 20:20:24
Subject: Re: [pester/docs] Updated generated docs-notice in command 
reference (PR #263)

**Comment by bravo-kernel** [comment]
It looks great but still not so much on mobile.

This would be more logical IMO, after that, we are good to merge.

    Caption: Do not edit this page
    Content: Update the related Pester 5.4.0 source code instead.

Make Pester 5.4.0 a link?

**Comment by fflaten** [comment]
> It looks great but still not so much on mobile.

Yeah, it got smaller, but still room for improvement. Will require page-specific css-change though.

> This would be more logical IMO, after that, we are good to merge.
> 
> ```
> Caption: Do not edit this page
> Content: Update the related Pester 5.4.0 source code instead.
> ```
> 
> Make Pester 5.4.0 a link?

Maybe it's just me, but "do not" etc. sounds a little strict/negative, so tried to avoid it. 🙂

**Comment by bravo-kernel** [comment]
I think `Do not edit this page` is a common instruction, identical to what one would see in an e.g. Windows form alert.

Making this smaller using CSS is probably not required if you make the suggested change ;)

**Comment by fflaten** [comment]
We'll need to drop a lot of text to improve on smaller phones, see last two. Good or did we loose too much context?

image

image

image

image

**Comment by bravo-kernel** [comment]
Number two is definitely the best one instruction-wise and I think we should go for that one.

If that means that we have to add some custom css for mobile to make it a little smaller, so be it (I can do that as well).

**Comment by bravo-kernel** [comment]
Does caption `Do not update this generated page` fit?

**Comment by fflaten** [comment]
> Does caption `Do not update this generated page` fit?

Yes.
image

**Comment by bravo-kernel** [comment]
Update the Pester 5.4.0 source instead.   ;)

**Comment by bravo-kernel** [comment]
Sorry mr @fflaten I forgot to think about `document.designMode = 'on'`

How about this?

image

Then append a simple line at the bottom of the page mentioning that the page is auto-generated. Can be a separate PR.

**Comment by fflaten** [comment]
> How about this?

My personal opinion though is still that "DO NOT .." is a bit hostile, especially when uppercased. As a comment in the MDX-source it'd be perfect, but 99% of readers are not going to contribute.

We already steal focus from the content they came to see, so **if** we end up prepending this I'd prefer it as a FYI about sub-par quality (formatting can be a bit funky) instead of a developer comment. Side by side:

image

> Then append a simple line at the bottom of the page mentioning that the page was auto-generated with the Pester version.

Good point. Hopefully we aren't that outdated, but will probably avoid a few comments when we forget to update after a patch-release. 👍

**Comment by bravo-kernel** [comment]
Fair points and I like the middle one but… pick the one you prefer and get this merged 👍🏼

Sent from my Mobile Device

**Comment by bravo-kernel** [comment]
Looks good to me. Hope you can handle one more suggestion.

I think the version information at the bottom should not be part of the `##Links` section. How about adding it to a `##Version` section like this. Should prevent any and all confusion.

image

**Comment by fflaten** [comment]
Hehe, of course 😁 I fully agree on that. Would you like to add a commit?

Should be a level 4 or 5 heading to exclude from table of contents. Alternatively just some bold text and linebreak. Feel free to rephrase it.

**Comment by bravo-kernel** [comment]
I would if I had the time but I am breaking my other activities trying to provide feedback already. We can also merge this, fix it another time.

**Comment by fflaten** [comment]
I'll look into it tomorrow. Nobody's waiting so no need to merge yet 🙂

**Comment by bravo-kernel** [comment]
Thanks, much appreciated 💯

**Comment by bravo-kernel** [comment]
Awesome job, thanks for hanging in there 💯

**Pull request merged**
