### PR TITLE
(maint) Add dev container

### PR DESCRIPTION
**Pull request by glennsarti**
This commit adds a development container to make it easier to test changes
independant of the developers current Pester setup.

### CODE REVIEW

**Comment by glennsarti** [comment]
Probably a duplicate of #65

**Comment by bravo-kernel** [comment]
We now have two suggestions for this and I must say this sounds very useful. I do think that we should add a page explaining how to use and configure this. 

If I understand correctly I would personally even create a new page directly beneath the "Installation" page, making it very visible to everybody that this is an option right from the start.

**Comment by glennsarti** [comment]
@bravo-kernel    Maybe.  It _feels_ like it should reference the Pester itself as it has a devcontainer already.  https://github.com/pester/Pester/commit/393f89a9eee2620449acbcea36acf976fc084979

**Comment by bravo-kernel** [comment]
Aha, I was assuming this was just a docker for this repo (to make it easy to e.g. test run the document generator). 

This is all new to me so perhaps @nohwnd can weigh in here.

**Comment by glennsarti** [comment]
This dev container is only for this repo, but was alluding to the documentation about dev containers could be shared.  Jsut like the other PR owner this isn't urgent or required.  Just nice to have.

**Comment by bravo-kernel** [comment]
Thanks, I see now. Perhaps we can add a more general section explaining how to use Docker some day.

**Comment by glennsarti** [comment]
_Typically_ I just reference VS Codes documentation (because I'm lazy :-) ) https://code.visualstudio.com/docs/remote/containers

**Comment by bravo-kernel** [comment]
That is a **very** good link 👍

**Comment by glennsarti** [comment]
Closed in favour of #65

**Pull request closed without merging**
