### PR TITLE
Add devcontainer support

### PR DESCRIPTION
**Pull request by fflaten**
This PR adds an initial devcontainer-configuration to the repo. A devcontainer provides an isolated docker container to develop, build and test the project which help contributors get up and running quickly with the required build tools.

Using VSCode + "Remote - Container" extension or Github Codespace, this is all seamless to the user and even the projects recommended extensions are installed.

PR also includes a pre-configured vscode task to start the docusaurus project with "polling mode" to support live-reloading (filesystem watcher mode didn't work in devcontainer)

### CODE REVIEW

**Comment by bravo-kernel** [comment]
@nohwnd bump

**Comment by fflaten** [comment]
This isn't critical, so open for discussion. Just figured I could submit a PR when I first created it locally. 🙂

**Comment by nohwnd** [comment]
Might be nice to add launch config to trigger the task. I had to look through the PR files to figure out how to start the server. and I think switching to the debugger tab and pressing play (or F5) is the first thing people will try.

**Comment by fflaten** [comment]
@nohwnd We can add that, just went with task as I didn't think debugging was necessary, but maybe @bravo-kernel benefits from that. Just needed local preview-environment when I added it.

Btw. did you try a no-cache run of this before merge? Getting a GPG error now on yarn-repo during apt-get update. Will create a new PR to fix it.

**Comment by fflaten** [comment]
> Btw. did you try a no-cache run of this before merge? Getting a GPG error now on yarn-repo during apt-get update. Will create a new PR to fix it.

Fix in #100

**Comment by nohwnd** [comment]
I did not, I just tried the task.

I also don’t think debug is necessary, but it’s a convenient way to run a task.

**Pull request merged**
