### PR TITLE
Update devcontainer to node 16

### PR DESCRIPTION
**Pull request by fflaten**
Updating devcontainer to match current prod environment.

Related #189

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Possibly related to this issue, could you try pinning `.nvmrc` to exact version `16.15.0`?

https://answers.netlify.com/t/node-v16-15-1-npm-v8-11-0-breaks-some-builds/64367/2

**Comment by fflaten** [comment]
Thanks. Will try it out in the SEO PR where CI is needed 😃

**Comment by bravo-kernel** [comment]
Another difference when comparing to my reference repo https://github.com/alt3/Docusaurus.Powershell is that the failing one has  "@docusaurus/theme-search-algolia": "^2.0.0-beta.21" in it's package.json.

The `Tip` on this page says it does not have to be there https://docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia. 

How about `yarn removing` that package and then pushing updated `package.json` and `yarn.lock` ?

>ps: I have asked for help in the Docusaurus discord as well

**Comment by bravo-kernel** [comment]
Is this one completed/ready to merge?

**Comment by fflaten** [comment]
Yes. Just used to last commit to trigger re-check 👍

**Comment by bravo-kernel** [comment]
Thanks for the updates and the patience. We should be good to go for a while now.

**Pull request merged**
