### PR TITLE
Update assertions.mdx to correct Throw section

### PR DESCRIPTION
**Pull request by mikepowell**
See https://github.com/pester/Pester/blob/62fa522645026e1a69d639e24d0af6ace56a7a15/src/functions/assertions/PesterThrow.ps1#L118 and https://github.com/pester/Pester/blob/62fa522645026e1a69d639e24d0af6ace56a7a15/src/functions/assertions/PesterThrow.ps1#L163

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Apologies for the lack of response. This looks good to me.

@nohwnd please confirm/merge.

**Review by nohwnd — APPROVED** [review]

**Comment by bravo-kernel** [comment]
@nohwnd apologies if this sounds insulting (and I did not check) but if this fix applied to v4... we need to update the corresponding file in `versioned_docs` (and thus not `/docs`).

**Comment by nohwnd** [comment]
No idea why this would insult me 🙂

I thought the change is for v5, because it uses -like. V4 uses string.contains: 

v5 
https://github.com/pester/Pester/blob/836565b1586a7008e9ba690003837ae9d6b6773a/src/functions/assertions/PesterThrow.ps1#L157-L164

v4

https://github.com/pester/Pester/blob/643a75d8022d04bb9ab5b6233e1791c365a21541/Functions/Assertions/PesterThrow.ps1#L147-L154

**Comment by bravo-kernel** [comment]
Right, just wanted to make sure and... did not want to make it sound like you are an idiot :)

**Pull request merged**
