### PR TITLE
Stuff from readme split into articles

### PR DESCRIPTION
**Pull request by nohwnd**
Move documentation from readme to their respective articles.

### CODE REVIEW

**Comment by nohwnd** [comment]
I've split up the stuff from readme into articles. Will have to rewrite some of them, to give them some form. And will probably rewrite mocking and assertions entirely in the future. @bravo-kernel do you know if we can add redirects when I move pages? E.g. if Assertions move from usage to their own section? I don't want to return 404 in case someone linked to that.

**Comment by bravo-kernel** [comment]
Good to see this in progress 💯.

If this concerns moving pages within Docusaurus I think redirecting should be possible. We should test of course but seems doable. https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

**Comment by nohwnd** [comment]
Some of the articles feel very partial, but getting this into the state I would like it to be would be at least two more days of work which I don't have now.

**Comment by nohwnd** [comment]
@bravo-kernel  please look into fixing the redirections as we discussed on discord. :)

**Pull request merged**
