### PR TITLE
updated example code fences

### PR DESCRIPTION
**Pull request by phbits**
Moved example code fences to include all provided code.

### CODE REVIEW

**Comment by fflaten** [comment]
Thanks for taking the time to point issue out. Unfortunately, these changes are not maintained directly in this repo. See https://github.com/pester/docs#contributing

We need to fix this directly in the function help or PlatyPS-conversion.

**Comment by bravo-kernel** [comment]
@phbits that page is auto-generated using the Get-Help found in the corresponding Pester function and should indeed be fixed [in this Pester source file](https://github.com/pester/Pester/blob/5a7d93ebdbe70d7614137239a8207192ee8bafc2/src/functions/Pester.SessionState.Mock.ps1). More about multi-line code fencing [here](https://docusaurus-powershell.netlify.app/docs/faq/multi-line-examples#code-fence-detection).

**Comment by fflaten** [comment]
I've added an issue for this (Pester/pester#1781) and a submitted a PR to fix these and similar issues in other functions 🙂

**Comment by nohwnd** [comment]
Thanks!

**Comment by phbits** [comment]
Thanks @fflaten and @nohwnd for adding the code fences to the source files via PR [pester/Pester#1782](https://github.com/pester/Pester/pull/1782). Now that the files have been updated, does a build process need to run to publish the changes?

After looking though the documentation provided by @bravo-kernel (Thanks!), who implemented a fix almost a year ago ([alt3/Docusaurus.Powershell/issues/14](https://github.com/alt3/Docusaurus.Powershell/issues/14#issuecomment-568552556)), the code fences should be automatically added via a regex match to examples starting with the case sensitive (Example|EXAMPLE) and ending with an empty line. The fall-back is to code fence only the first line after (Example|EXAMPLE) which has been the result thus far. This leads me to believe that something needs to be fixed in the build process that creates the documentation. Though complex code examples that include empty lines will still need the manual addition of a code fence.

I'm new to Pester, docusaurus, etc., so it's taking time to get up to speed. Long term I think it makes sense to identify what is causing the code fences to "fall-back" mode. Interested to hear your feedback.

**Comment by fflaten** [comment]
These examples had empty lines in the code which is why they broke. I don't think the command docs is auto-pushed. If so, the manual update should probably wait for 5.1.0 release to include new functions.

**Comment by bravo-kernel** [comment]
@fflaten you are right, there is no issue with empty white lines in multi-line code blocks, as long as they are code fenced correctly.

We still need to create a new CI build process to handle generating the docs after every merge. [See this file for how it works](https://github.com/pester/docs/blob/master/generate-command-reference.ps1). You should be able to generate them locally as well.

**Comment by fflaten** [comment]
Yeah I ran that locally and noticed the about_* help and "Should" etc. links breaks the site. Compilation doesn't like links without URLs. So we need to clean that up first (in a new issue that is) or fix platt/docuaurus.powershell to make sure they aren't converted to empty links 😊

**Comment by bravo-kernel** [comment]
Agreed and I think it should actually be "real" links. Those "about_help" links make no sense.

**Comment by fflaten** [comment]
They actually do make sense, it's just that the markdown-conversion doesn't support them in a proper way.
`.LINK` in comment-based help is related topic (like about_*, Should ++) first, URI second (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.1#link)

Either way, this belongs in a new issue that one of us should probably open in one or both repos 🙂

**Comment by bravo-kernel** [comment]
IMO... if it is supposed to be a link, just make it a plain old (https://) link in the Get-Help. Recognizable for everyone, easy to reason about and highly maintainable for e.g. versioning.

**Comment by fflaten** [comment]
I don't disagree personally, but you're only looking at it without your PowerShell-glasses. 😄
The help-system was primarily created for help available in the terminal, including offline environments. So links are meant to reference other relevant help-articles in the PowerShell session. The `-Online` parameter is used to access the same (or better) help on the web. Even though we like cool websites, we can't ignore users working in the terminal and it's our job to provide useful link/references in both cases.

**Comment by bravo-kernel** [comment]
I totally agree on the terminal users but I am suggesting best of both worlds.

```powershell
.LINK
[Should](https://pester.dev/docs/v4/commands/Should)
```

**Comment by fflaten** [comment]
Ahh, using markdown directly. AFAIK the links aren't clickable in any way in the terminal, so that might work. 👍  E.g.
```
.LINK
[about_Should](https://pester.dev/docs/usage/assertions)
```
Unless people would expect them to contain the same information, but then again the probably should do that already.

Wanna move this to a new issue in the Pester-repo so we can get some input from nohwnd and other users?

**Comment by bravo-kernel** [comment]
Yes, markdown is fully supported within the Get-Help so that opens some options. 

Perhaps you can help me out here because, and this is most likely a knowledge gap on my end, I simply do not understand what that `about_Should` means semantically. If I see `about_Should` in my console, what does it point to?

**Comment by bravo-kernel** [comment]
Aha, it points to those pesky text files in `en_US` correct?

E.g. https://www.powershellgallery.com/packages/Pester/4.10.1/Content/en-US%5Cabout_Should.help.txt

Are those even there in the Pester distribution?

**Comment by fflaten** [comment]
Yes, see `Get-Help about_Should`

**Comment by bravo-kernel** [comment]
Exactly. I remember again, initially from other modules like Module-Builder and to be honest, those were almost always outdated as well.

This is why I am putting in [this generic alternative](https://github.com/alt3/Docusaurus.Powershell/blob/master/Source/en-US/aboutAlt3.Docusaurus.Powershell.help.txt) myself, simply pointing them to the correct online resource.

**Comment by bravo-kernel** [comment]
@nohwnd there are a couple of the `about` references breaking the MDX rendering. I really think we should start with making a generic en_us about help file as described above. In time, if the need for text-based about help is still there, it can be a separate action.

AfterAll:

- delete link to self: [https://pester.dev/docs/commands/AfterAll](https://pester.dev/docs/commands/AfterAll)
- this one breaks the rendering, should be separate links or deleted: [about_BeforeEach_AfterEach]() 

AfterEach:

- this one breaks the rendering, should be separate links or deleted: [about_BeforeEach_AfterEach]()

BeforeAll:

- this one breaks the rendering, should be separate links or deleted: [about_BeforeEach_AfterEach]()

BeforeEach:

- this one breaks the rendering, should be separate links or deleted: [about_BeforeEach_AfterEach]()

Describe:

- should be fixed or deleted: [about_Should]()
- should be fixed or deleted: [about_Mocking]()
- should be fixed or deleted: [about_TestDrive]()

Should:

- [about_Should]()
- [about_Pester]()

**Comment by bravo-kernel** [comment]
As in this rendered mdx for Should

image

**Comment by bravo-kernel** [comment]
Created a Pester PR removing the outdated links. https://github.com/pester/Pester/pull/1805

**Pull request closed without merging**
