### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by martincostello**
Fixes two small typos.

### CODE REVIEW

**Comment by fflaten** [comment]
Thanks for spotting and fixing those!

Unfortunately all files under `docs/commands/*` are generated so this would revert on next module release. Would you mind submitting a PR in the pester-repo to fix the source? 🙂 
https://github.com/pester/Pester/blob/main/src/functions/Context.ps1
https://github.com/pester/Pester/blob/main/src/functions/Describe.ps1

**Comment by martincostello** [comment]
Sure, no problem. I just clicked the edit button in the site and it brought me here so assumed that was what I needed to change 😅

**Comment by martincostello** [comment]
https://github.com/pester/Pester/pull/2326

**Comment by fflaten** [comment]
> Sure, no problem. I just clicked the edit button in the site and it brought me here so assumed that was what I needed to change 😅

Thanks! 

Edit button where exactly? On another page? The Github link in the navigation bar? Just to figure out if we can make this more intuitive. 🙂 

On the command reference-pages the edit button should be replaced with a notice about this as it's a bit confusing.

**Comment by martincostello** [comment]
I saw the typo, then just clicked the GitHub link at the top of the page. I didn't scroll all the way down to the bottom where the EDIT THIS PAGE section that points to pester/Pester is.

image

**Comment by bravo-kernel** [comment]
Aha, thank you for clarifying that.

@fflaten the command pages do not have an edit button because of this front matter `custom_edit_url: null`

I do see that the current disclaimer at the bottom of the page ([added here](https://github.com/pester/docs/blob/master/generate-command-reference.ps1#L92)) could cause confusion. Perhaps we can:

- Replace it with an admonition
- Change to [PrependMarkdown](https://docusaurus-powershell.vercel.app/docs/commands/New-DocusaurusHelp#-prependmarkdown)

**Comment by fflaten** [comment]
@martincostello Thanks!
@bravo-kernel Maybe both: prepended admonition. If it looks good and does not take up to much vertical space.

**Pull request closed without merging**
