### PR TITLE
Use docsearch api keys

### PR DESCRIPTION
**Pull request by nohwnd**

### CODE REVIEW

**Comment by bravo-kernel** [comment]
I think this should do it but if you want to be sure I can merge mine, probably tomorrow.

**Review by bravo-kernel — APPROVED** [review]

**Comment by bravo-kernel** [comment]
I think the website needs to be updated to docusaurus 2.0.0-beta.9 as well. 

Will you be able to take care of that?

**Comment by nohwnd** [comment]
Merge after #154

**Comment by nohwnd** [comment]
Omg no, this is not azure devops :D

**Pull request merged**
