### PR TITLE
Fix links on quick start guide

### PR DESCRIPTION
**Pull request by ssomers**
First thing we newcomers notice is that the links are broken.

### CODE REVIEW

**Comment by nohwnd** [comment]
Thanks.

I see them working in the page that is live on pester.dev, but they don’t work after your change (in the netlify preview). How did you find the issue and test this?

**Comment by ssomers** [comment]
Oooh... I landed at https://pester.dev/docs/quick-start/ and the links are broken. But if one omits the trailing slash, like when starting from pester.dev/, it works fine.

**Comment by fflaten** [comment]
> Oooh... I landed at https://pester.dev/docs/quick-start/ and the links are broken. But if one omits the trailing slash, like when starting from pester.dev/, it works fine.

Thanks for identifying this. Looks like netlify might prefer that we use trailing slash. It can redirect to trailing slash but not remove it. Maybe something we should consider. 🙂

**Comment by fflaten** [comment]
No worries, can reproduce by adding it manually. Just something we can be aware of for now and consider improving so everything works regardless. 👍

**Pull request closed without merging**
