### PR TITLE
Add docs for Output options

### LINKED ISSUE #124: Add Output usage-doc
We might want to add a page showing the difference in output verbosity and the future stacktrace verbosity.

IIRC this is only mentioned quickly in VSCode + Diagnostic-level in Troubleshooting.

### PR DESCRIPTION
**Pull request by fflaten**
Adds a new page explaining the configuration options to customize the console output.
Fix #124

Page includes details about the unreleased `Output.StackTraceVerbosity` and `Output.CIFormat` options.

### CODE REVIEW

**Comment by nohwnd** [comment]
Cool does this need more work or we are waiting for 5.3 to be released?

**Comment by fflaten** [comment]
Mostly waiting on some beta-releases just in case we change the behavior of the new options in some way.

**Comment by fflaten** [comment]
Ready for review. Any feedback on the text?

I added a discord community-link to match the readme-PR in pester-repo. Can remove or split out if necessary.

**Comment by nohwnd** [comment]
@fflaten  will try to review in upcoming days. I am trying to get back on top of my notifications at least :D And assignment will be next.

**Review by nohwnd — APPROVED** [review]

**Comment by nohwnd** [comment]
> Focus on successful containers and failed tests/blocks.

This is a great way to describe it. :)

**Pull request merged**
